sudo: required

services:
  - docker

# show correct language tag in Travis CI build
language: cpp

env:
  matrix:
    - INSTALL_ROS: true    ## use ubuntu docker image from docker hub


before_install:
  - pwd
  # this cmd will run docker, and copy the contents of the repo root directory to /home/ivrcscripts folder
  - docker run -d -it --name ci_xenial -v $(pwd):/home/ivrcscripts aragdoll/docker_ubuntu:xenial

install:
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_grid_map.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_gtest.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_ipopt.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_latex.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_libccd_fcl.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_nlopt.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_octomap.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_opencv3.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_ros.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_snopt.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_sougou.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_vrep.sh"
  - docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_github_lfs.sh"

script:
  - docker exec -it ci_xenial /bin/bash -c "echo 'CI is working!'"



notifications:
    email: false
