sudo: required

services:
  - docker

# show correct language tag in Travis CI build
language: cpp

env:
  matrix:
    - INSTALL_ROS: false    ## use ubuntu docker image from docker hub
    - INSTALL_ROS: true


before_install:
  # this cmd will run docker, and copy the contents of the repo root directory to /home/ivrcscripts folder
  # get the docker running
  - if [ $INSTALL_ROS == 'true' ]; then
      docker run -d -it --name ci_xenial -v $(pwd):/home/ivrcscripts aragdoll/docker_ubuntu:xenial;
    else
      docker run -d --name ci_xenial_ros -v $(pwd):/home/ivrcscripts aragdoll/docker_ubuntu:xenial_ros_kinetic;
    fi


install:
  - if [ $INSTALL_ROS == 'false' ]; then
      docker exec -it ci_xenial /bin/bash -c "cd /home/ivrcscripts;
      ./install_gtest.sh; 
      ./install_libccd_fcl.sh;
      ./install_nlopt.sh;
      ./install_octomap.sh";
      ./install_sougou.sh y;
    else
      docker exec -it ci_xenial_ros /bin/bash -c "cd /home/ivrcscripts;
      ./install_grid_map.sh;
      ./install_geographic.sh";
    fi
  #- docker exec -it ci_xenial /bin/bash -c "bash /home/ivrcscripts/install_grid_map.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_gtest.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_ipopt.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_latex.sh" # do not test this in travis
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_libccd_fcl.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_nlopt.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_octomap.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_opencv3.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_ros.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_snopt.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_sougou.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_vrep.sh"
  #- docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/install_github_lfs.sh"

script:
  - if [ $INSTALL_ROS == 'true' ]; then
      docker exec -it ci_xenial /bin/bash -c "echo 'Xenial without ROS CI is working!'";
    else
      docker exec -it ci_xenial_ros /bin/bash -c "echo 'Xenial with ROS CI is working!'";
    fi




notifications:
    email: false
