sudo: required

services:
  - docker

# show correct language tag in Travis CI build
language: cpp

env:
  matrix:
    - SCRIPT_NAME: install_bit_source_list.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_ceres.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_cppad.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_github_lfs.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_gtest.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_libccd_fcl.sh
      INSTALL_ROS: false

   - SCRIPT_NAME: install_nlopt.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_octomap.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_snopt.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_sogou.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_vrep.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_ros.sh
      INSTALL_ROS: false

    - SCRIPT_NAME: install_geographic.sh
      INSTALL_ROS: true

    - SCRIPT_NAME: install_grid_map.sh
      INSTALL_ROS: true

    - SCRIPT_NAME: install_ipopt.sh
      INSTALL_ROS: false

before_install:
  # this cmd will run docker, and copy the contents of the repo root directory to /home/ivrcscripts folder
  # get the docker running
  - if [ $INSTALL_ROS == 'false' ]; then
      docker run -d -it --name ci_xenial -v $(pwd):/home/ivrcscripts aragdoll/docker_ubuntu:xenial;
    else
      docker run -d -it --name ci_xenial_ros -v $(pwd):/home/ivrcscripts aragdoll/docker_ubuntu:xenial_ros_kinetic;
    fi

install:
  - if [ $INSTALL_ROS == 'false' ]; then
      docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/$SCRIPT_NAME";
    else
      docker exec -it ci_xenial_ros /bin/bash -c "/home/ivrcscripts/$SCRIPT_NAME";
    fi

script:
  - if [ $INSTALL_ROS == 'false' ]; then
      docker exec -it ci_xenial /bin/bash -c "echo 'Xenial without ROS CI is working!'";
    else
      docker exec -it ci_xenial_ros /bin/bash -c "echo 'Xenial with ROS CI is working!'";
    fi




notifications:
    email: false
