sudo: required

services:
  - docker

# show correct language tag in Travis CI build.
language: cpp

env:
  matrix:
    - NAME: install_bit_source_list.sh # 1
      WITH_ROS: false
    - NAME: install_ceres.sh  # 2
      WITH_ROS: false
    - NAME: install_cppad.sh  # 3
      WITH_ROS: false
    - NAME: install_github_lfs.sh # 4
      WITH_ROS: false
    - NAME: install_gtest.sh   # 5
      WITH_ROS: false
    - NAME: install_libccd_fcl.sh  # 6
      WITH_ROS: false
    - NAME: install_nlopt.sh  # 7
      WITH_ROS: false
    - NAME: install_sogou.sh  # 8
      WITH_ROS: false
    - NAME: install_wubi.sh  # 9
      WITH_ROS: false
    - NAME: install_vrep.sh  # 10
      WITH_ROS: false
    - NAME: install_ros.sh  # 11
      WITH_ROS: false
    - NAME: install_geographic.sh  # 12
      WITH_ROS: false
    - NAME: install_grid_map.sh   # 13
      WITH_ROS: true
    - NAME: install_ipopt.sh  # 14
      WITH_ROS: false
    - NAME: install_nlopt.sh  # 15 
      WITH_ROS: false

before_install:
  # this cmd will run docker, and copy the contents of the repo root directory to /home/ivrcscripts folder
  # get the docker running
  - if [ $WITH_ROS == 'false' ]; then
      docker run -d -it --name ci_xenial -v $(pwd):/home/ivrcscripts aragdoll/docker_ubuntu:xenial;
    else
      docker run -d -it --name ci_xenial_ros -v $(pwd):/home/ivrcscripts aragdoll/docker_ubuntu:xenial_ros_kinetic;
    fi

install:
  - if [ $WITH_ROS == 'false' ]; then
      docker exec -it ci_xenial /bin/bash -c "/home/ivrcscripts/installers/$NAME";
    else
      docker exec -it ci_xenial_ros /bin/bash -c "/home/ivrcscripts/installers/$NAME";
    fi

script:
  - if [ $WITH_ROS == 'false' ]; then
      docker exec -it ci_xenial /bin/bash -c "echo 'Xenial without ROS CI is working!'";
    else
      docker exec -it ci_xenial_ros /bin/bash -c "echo 'Xenial with ROS CI is working!'";
    fi


notifications:
    email: false
